### ISSUE TITLE
Provide docker-compose file

### ISSUE THREAD

**Issue by Klausmd5** [gjuniioor/docker-bricks#2]
Please provide the following docker-compose file in the README:

```
version: '3.9'

services:

  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example

    ports:
      - 3306:3306

  bricks:
    container_name: bricks
    image: gjuniioor/owasp-bricks

    ports:
      - 80:80

```
